### ISSUE TITLE
Compression suggestion

### ISSUE THREAD

**Issue by qistoph** [LenShustek/miditones#17]
Dear @LenShustek,

Thanks for your support on the other issue and merging my PR. I've been working on another idea that might be of interest to you. I've tried to implement it myself, but find a little too hard to understand the code for the time I currently want to invest in this idea.

Converting the midi file I wanted to play with an ATtiny85 I'm running out of space. Then when I was looking at the midinotes_scroll, I've found quite a lot of 1ms moments. I've tried to filter these out and merge the line above and lines below that are the same (in the scroll).

This change just skips generating the lines with a duration of 1ms or less. This doesn't merge or even add the now missing 1ms to the previous line.
```diff
diff --git a/miditones.c b/miditones.c
index 2dd74cd..ed06b41 100644
--- a/miditones.c
+++ b/miditones.c
@@ -1172,7 +1172,7 @@ int main (int argc, char *argv[]) {
          if (delta_time) {
             /* Convert ticks to milliseconds based on the current tempo */
             delta_msec = ((unsigned long long) delta_time * tempo) / ticks_per_beat / 1000;
-            if (delta_msec) { // if time delay didn't round down to zero msec
+            if (delta_msec > 1) { // if time delay didn't round down to zero msec
                gen_stopnotes(); /* first check if any tone generators have "stop note" commands pending */
                if (loggen)
                   fprintf (logfile, "->Delay %ld msec (%ld ticks)\n", delta_msec, delta_time);
```

I have created a python script to parse a midinotes binary and filter these events out and merge the lines as described. The resulting audio sounds just as good as the original, but it's size is reduced from `7266 bytes` to just `3251 bytes` (fitting my ATtiny85's memory easily).

Ultimately I'm thinking of making this configurable with a commandline argument, something like:
`-mx   merge events shorter than x milliseconds (produces less output)`

**Comment by LenShustek** [comment]
I'm always excited by the notion of increasing time or space efficiency, so let me think about that. 

I'm surprised at how much space you were able to save. If that is common, I like the idea of adding an option that lets you merge events that are within x milliseconds of each other, to save space with minimal effect on the resulting sound. But the time that is skipped must be remembered -- in microseconds -- and eventually accounted for, so that cumulative errors don't cause the tone generators to drift out of synchronization.

Fitting into an ATtiny is indeed challenging. I did that a few years ago
   https://github.com/LenShustek/ATtiny-playtune
   https://www.evilmadscientist.com/2013/musical-menorah/
but had to change from the ATtiny2313 with 2K bytes of program memory to the pin-compatible ATtiny4313 with 4K bytes in order to fit both the program and the music.

**Comment by qistoph** [comment]
I absolutely agree that it would be best to compensate for the drift. Even though in my case the drift is only 491ms, on a track of 273.865 seconds. Especially if the option would allow someone to merge events even longer than just 1ms, compensating the drift is essential.

In my script I did this by extending the previous event with 1ms for every removed 1ms-event.

The scroll of my file start like this:
```
125       0.000    3C      
373       0.125    3C    4E
  1       0.498            
373       0.499    3C    4E
  1       0.872            
373       0.873    3C    4E
  1       1.246            
373       1.247    3C    4E
  1       1.620            
373       1.621    3C    4E
  1       1.994            
```

The 1ms pauses between notes would replay the note, instead of extending it. This would influence the sound (I think) if the generators would produce different sounds throughout the duration of the note. If I'm correct this is not the case for players using miditones, right?

**Comment by LenShustek** [comment]
A couple of days ago I privately sent you a beta test version that implements the -m "merge notes" idea. When you get a chance, let me know what you think.

**Comment by qistoph** [comment]
Hi @LenShustek, I never got your private message... Could you resend it? Or upload it in a new branch to Github?

**Comment by LenShustek** [comment]
Ok, resent.

**Comment by qistoph** [comment]
Nope... Stil haven't got it... Did you include the the .exe in a .zip? Maybe Gmail is rejecting the mail because of the attachment.

I won't mind if you'd put it in a branch, here on Github.

**Comment by LenShustek** [comment]
Yes, I had included the .exe file as an attachment.
I barely know how to use Github, but I tried to create a test branch. Let me know if I succeeded.

I'm on to more changes. Listening to the difference between how your MIDI file sounds and how it is rendered in Playtune motivated me to start working on yet another optional feature: I'm adding a "-relx" parameter, which causes notes to be released (stopped) x milliseconds before the "end note" event in the score. That makes the notes sound separate from each other, and is a start on implementing some primitive ADSR (attack-delay-sustain-release) support. I could do even more when the -v option is used to encode volume information.

I've got it partially working. To do it right I need to add an output reorder queue so that, in some circumstances, the "stop note" command can appear before later "start note" commands. But even without that, it makes your example sound much closer to the MIDI file.

The downside is that it has the opposite effect from -mx on the size of the generated codestream: it gets bigger because of the extra delay commands. But for some applications that's ok. It helps a little that you can say, for example, both -m2 and -rel10.

**Comment by qistoph** [comment]
Yes, found it! This is exactly the kind of branch that I meant. If you want to know more about branching/merging, the [Git Pro Book](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging) is an absolute must read. It's available online for free.

I've done some tests with and without `-m` and the results look good to me. I have reviewed the results only visually, by comparing scroll outputs. Currently I don't have hardware with me to test the actual audio.

**Comment by LenShustek** [comment]
Well, I got inspired by your request, and it led to a major rewrite. I added out-of-order queuing of events that allows not only merging (now specified with -delaymin) but also note attack/release/sustain timing. 

I think I may have gotten a little carried away, but it was fun...

**Comment by qistoph** [comment]
Wow, that sounds really nice! I'll definitely check it out soon!
