### ISSUE TITLE
Even after i downloaded the missing dll ,it just open and closes and i cant even type

### ISSUE THREAD

**Issue by Juarezdoposto** [LenShustek/miditones#22]
I tried to execute the miditones from the exe file and the cmd,both give a error of missing 2 dll,vcruntime140d and ucrtbased.
I downloaded the dll and put them together on the miditones folder,i execute,it gave no errors,but simply open and closes i cant even type

**Comment by LenShustek** [comment]
That's an indication that you are running the "debug" version on a computer without Visual Studio installed. I had made the mistake of posting the debug version (instead of the "release" version) a long time ago. But the version there now, from May 28, 2019, is the release version. Are you sure you're using that one? I just tried it on a computer that doesn't have Visual Studio and it seems to work ok.

**Comment by Juarezdoposto** [comment]
I downloaded again the last release,and the problem still the same,my firewall isnt preventing the execution beacause i gave all the permissions,i still dont know what it can be

**Comment by Juarezdoposto** [comment]
I restart and runned it from the folder on the cmd and you message appeared,i think it was it thanks

**Comment by LenShustek** [comment]
I don't understand what you changed, but it doesn't matter -- I'm glad it's working for you now.
