### ISSUE TITLE
Strange pauses when playing midis

### ISSUE THREAD

**Issue by joeybab3** [LenShustek/miditones#7]
I noticed when I upgraded today, that occasionally in my midi file(which I wrote) it would sort of have these strange pauses or play the notes too long, then go back to normal...
I will try and get a video tomorrow of the issues, I'm using a nano btw

[WF_CLUTTERFUNK_7.zip](https://github.com/LenShustek/miditones/files/355862/WF_CLUTTERFUNK_7.zip)

**Comment by LenShustek** [comment]
That's not good. I'll look into it.
What did you upgrade? You're using the earliest version of miditones, version 1.1. But that's fine; once I figured out that you must have used the -t6 and -s1 parameters, I generated the same output with the latest version.
So was it arduino-playtune that you upgraded? Can you tell me where the bad timing occurs?

**Comment by LenShustek** [comment]
I just noticed you said you are using a Nano.  That uses the ATmega328 processor which has 3 timers, so it can play only 3 notes at once. But your midi file uses 7 note channels. Could it be that the "strange pauses" are just notes that can't play because there aren't enough channels to play all the notes?

I compiled your file for an Arduino Mega 2560 that has 6 channels, and I had it play at the same time I played the midi file on my computer. They were synchronized almost perfectly!

I've thought about making a version of playtune that uses polling instead of timers to create the music, like I did a few years ago for the Evil Mad Scientist menorah.  See https://github.com/LenShustek/ATtiny-playtune.  With a fast enough processor, you can play an arbitrary number of channels.

Should I work on that?  It would be fun...

**Comment by joeybab3** [comment]
I just realized it used 1.1 miditones, I'll recompile and let you know how it goes...
